export const TOOGGLE_MENU_STATUS = 'TOOGGLE_MENU_STATUS'
export const TOOGGLE_SEACH_STATUS = 'TOOGGLE_SEACH_STATUS'
export const GET_CHAT_LEST = 'GET_CHAT_LEST'
export const GET_GROUP_LEST = 'GET_GROUP_LEST'
